added SchemaConverter interface for controlling Schema generation
sashirestela/simple-openai pull request #160
Opened 2024-07-18 07:54 UTC by asafbennatan

solves #159 

1.added `SchemaConverter `interface for controlling Schema generation
2.added `DefaultSchemaConverter `for running the default (same logic that we had before in `JsonSchemaUtil`) - note this also improves performance as previously schema creator was created per serialization
3. `JsonSchemaUtil `is not really necessary anymore but kept to be compatible;

2024-07-19 04:09 UTC, sashirestela reviewed
Please, follow the guidelines for contributions: https://github.com/sashirestela/simple-openai/blob/main/CONTRIBUTING.md

2024-07-19 09:16 UTC, asafbennatan commented
hi @sashirestela , i assume you refer to the code formatting ? (if not please let me know)

i tried running the spotless plugin on the PR's code , but it does not report any issue:

```
 mvn spotless:check
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< io.github.sashirestela:simple-openai >----------------
[INFO] Building simple-openai 3.5.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- spotless-maven-plugin:2.43.0:check (default-cli) @ simple-openai ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.526 s
[INFO] Finished at: 2024-07-19T12:13:42+03:00
[INFO] ------------------------------------------------------------------------

```

```
mvn spotless:apply                                                        
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< io.github.sashirestela:simple-openai >----------------
[INFO] Building simple-openai 3.5.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- spotless-maven-plugin:2.43.0:apply (default-cli) @ simple-openai ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.540 s
[INFO] Finished at: 2024-07-19T12:13:52+03:00
[INFO] ------------------------------------------------------------------------

```

2024-07-19 09:30 UTC, asafbennatan commented
fixed formatting , anything else ?

2024-07-20 13:32 UTC, sashirestela commented
@asafbennatan The build has failed. Take a look at:

2024-07-20 15:07 UTC, sashirestela requested changes

2024-07-20 15:07 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/common/function/FunctionDef.java
> +    @Builder.Default
Please, add a breakline before, for better readability

2024-07-20 20:57 UTC, asafbennatan commented
@sashirestela done , please review

2024-07-20 22:22 UTC, sashirestela approved these changes

2024-07-20 23:48 UTC, merged