Assistants API support for Azure OpenAI
sashirestela/simple-openai pull request #72
Opened 2024-04-04 03:33 UTC by the-gigi

- Implement the Files, Assistants and Threads API endpoints in SimpleOpenAIAzure
- Update ChatAzureServiceDemo to use deployments that are available to test
- Create new AssistantAzureService Demo
- Switch to blocking mode for vision (streaming returns 200 response, but with no choices)
- Improved tests a little
- Also minor change to rundemo.sh to make it bash3.2 compatible (default on MacOS) - the previous code requires bash 4.0

Ran spotless check.
```
❯ mvn spotless:check
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< io.github.sashirestela:simple-openai >----------------
[INFO] Building simple-openai 2.1.1
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- spotless:2.43.0:check (default-cli) @ simple-openai ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.646 s
[INFO] Finished at: 2024-04-03T20:33:04-07:00
[INFO] ------------------------------------------------------------------------
```

2024-04-11 18:23 UTC, sashirestela requested changes
Please, take actions on the 10 observations.

2024-04-11 18:23 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java
Please, let's divide the `requestInterceptor` code in chunks of functions to get the new url, the new body for Json, the new body for Map. In addition, declare constants to use instead of literal values.

2024-04-11 18:23 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java
> +    public OpenAI.Files files() {
Add @Override

2024-04-11 18:23 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java
> +    public OpenAIBeta.Assistants assistants() {
Add @Override

2024-04-11 18:23 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java
> +    public OpenAIBeta.Threads threads() {
Add @Override

2024-04-11 18:23 UTC, sashirestela commented on README.md
Add a note in the Azure section to indicate what functionalities are really working. For example chat/completions has many functionalities but Azure is not supporting all of them.

2024-04-11 18:23 UTC, sashirestela commented on src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java
Increase the test coverage of this class. You have added code but unit tests are not covering it.

2024-04-11 20:18 UTC, the-gigi commented on rundemo.sh
> +  service=$(echo "$1" | awk '{ print toupper(substr($0, 1, 1)) substr($0, 2) }')
I explained in the PR description. the current version doesn't work on bash3.2, which is the default bash version on Mac. This change works make it work out of the box without requiring the user to upgrade to bash 4+. A lot of people (like me) use zsh and never upgrade bash, so this just creates friction.

```
bash-3.2$ echo "abc" | awk '{ print toupper(substr($0, 1, 1)) substr($0, 2) }'
Abc
bash-3.2$ "${abc^}"
bash: ${abc^}: bad substitution
```

2024-04-11 20:19 UTC, the-gigi commented on src/demo/java/io/github/sashirestela/openai/demo/ChatAzureServiceDemo.java
> +        var chatResponse = openAI.chatCompletions().create(chatRequest).join();
It supported it for gpt-35-turbo

2024-04-12 04:46 UTC, the-gigi commented on src/demo/java/io/github/sashirestela/openai/demo/ChatAzureServiceDemo.java
> +        var chatResponse = openAI.chatCompletions().create(chatRequest).join();
I confirmed it against the latest gpt-4-turbo and gpt-4 vision preview  models

the response from streaming returns with 200 status code and valid json, but no data. the choices array is empty. 
![image](https://github.com/sashirestela/simple-openai/assets/1409590/71bae7d1-e069-46f1-9c3b-020cebbd4cf0)

2024-04-12 04:47 UTC, the-gigi commented on src/demo/java/io/github/sashirestela/openai/demo/ChatAzureServiceDemo.java
> +        var chatResponse = openAI.chatCompletions().create(chatRequest).join();
same answer

2024-04-12 08:23 UTC, the-gigi commented
@sashirestela fixed all observations and answered some of the questions. ready for re-review

2024-04-12 19:18 UTC, sashirestela requested changes
Please, take action on the new 8 observations.

2024-04-12 19:18 UTC, sashirestela commented on README.md
> +    * chatAzure
Include `chatAnyscale`

2024-04-15 14:47 UTC, sashirestela approved these changes

2024-04-15 14:47 UTC, merged